void Delayms(unsigned int MS);
void D12_init(void);
void OutB(unsigned char cmd,unsigned char dat);
unsigned char InB(void);
void Set_addren(unsigned char addr, unsigned char enable);
void Set_EPen(unsigned char enable);
void Set_mode(unsigned char config,unsigned char clkdiv);
void Set_DMA(unsigned char bMode);
unsigned int Read_IntR(void);
unsigned char Sel_EP(unsigned char endp);
unsigned char Read_EPsta(unsigned char endp);
unsigned char Read_LttransSta(unsigned char endp);
void Set_EPsta(unsigned char endp,unsigned char stall);
void Set_Sresume(void);
unsigned char Read_EP(unsigned char endp,unsigned char len,unsigned char * buf);
unsigned char Write_EP(unsigned char endp,unsigned char len,unsigned char * buf);
void Ack_EP(unsigned char endp);
void Clear_buf(unsigned char endp);
void Stall_ep0(void);
void S_trans(unsigned char * buf, unsigned char len);

void Ep0_rxdone(void);
void Ep0_txdone(void);
void Ep1_txdone(void);
void Ep1_rxdone(void);
void Ep2_txdone(void);
void Ep2_rxdone(void);

void Reserved(void);
void Get_status(void);
void Clr_feature(void);
void Set_feature(void);
void Set_addr(void);
void Get_descriptor(void);
void Get_config(void);
void Set_config(void);
void Get_interface(void);
void Set_interface(void);
void USB_reconnect(void);
void Control_handler(void);
void Uart_sendB(unsigned char sendB);
unsigned int Read_chipID(void);
